export const week19 = [
  {
    Brand: "EDUCATION EXPO",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 607,
    "Radio One": 0,
    "Red FM": 631,
    Total: 1238,
  },
  {
    Brand: "ATLANTIC WATER WORLD",
    Sector: "ENTERTAINMENT",
    "Radio City": 634,
    "Radio Mirchi": 467,
    "Radio One": 0,
    "Red FM": 0,
    Total: 1101,
  },
  {
    Brand: "UNISON JEWELS",
    Sector: "ACCESSORIES",
    "Radio City": 378,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 419,
    Total: 797,
  },
  {
    Brand: "SBI",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 139,
    "Radio One": 291,
    "Red FM": 271,
    Total: 701,
  },
  {
    Brand: "MARUTI SUZUKI",
    Sector: "AUTOMOBILE",
    "Radio City": 85,
    "Radio Mirchi": 116,
    "Radio One": 118,
    "Red FM": 215,
    Total: 534,
  },
  {
    Brand: "VIMAL",
    Sector: "FMCG",
    "Radio City": 147,
    "Radio Mirchi": 131,
    "Radio One": 113,
    "Red FM": 127,
    Total: 518,
  },
  {
    Brand: "SPINNY",
    Sector: "AUTOMOBILE",
    "Radio City": 144,
    "Radio Mirchi": 116,
    "Radio One": 147,
    "Red FM": 110,
    Total: 517,
  },
  {
    Brand: "WORLDS OF WONDER (WOW)",
    Sector: "ENTERTAINMENT",
    "Radio City": 292,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 181,
    Total: 473,
  },
  {
    Brand: "LG",
    Sector: "CONSUMER DURABLES",
    "Radio City": 177,
    "Radio Mirchi": 169,
    "Radio One": 74,
    "Red FM": 44,
    Total: 464,
  },
  {
    Brand: "HONDA",
    Sector: "AUTOMOBILE",
    "Radio City": 107,
    "Radio Mirchi": 108,
    "Radio One": 0,
    "Red FM": 160,
    Total: 375,
  },
  {
    Brand: "RAJDHANI",
    Sector: "FMCG",
    "Radio City": 118,
    "Radio Mirchi": 110,
    "Radio One": 0,
    "Red FM": 125,
    Total: 353,
  },
  {
    Brand: "SANSKAR SHIKSHA SANGH",
    Sector: "EDUCATION",
    "Radio City": 351,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 351,
  },
  {
    Brand: "ROF",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 346,
    Total: 346,
  },
  {
    Brand: "MG",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 145,
    "Radio One": 0,
    "Red FM": 199,
    Total: 344,
  },
  {
    Brand: "NISSAN",
    Sector: "AUTOMOBILE",
    "Radio City": 298,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 298,
  },
  {
    Brand: "K.R. MANGALAM UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 140,
    "Radio One": 0,
    "Red FM": 136,
    Total: 276,
  },
  {
    Brand: "VINRA GROUP",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 259,
    Total: 259,
  },
  {
    Brand: "GRAPHIC ERA UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 65,
    "Radio Mirchi": 96,
    "Radio One": 0,
    "Red FM": 93,
    Total: 254,
  },
  {
    Brand: "DAAWAT",
    Sector: "FMCG",
    "Radio City": 129,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 122,
    Total: 251,
  },
  {
    Brand: "DAIKIN",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 121,
    "Radio One": 0,
    "Red FM": 120,
    Total: 241,
  },
  {
    Brand: "CANARA BANK",
    Sector: "FINANCE",
    "Radio City": 179,
    "Radio Mirchi": 45,
    "Radio One": 0,
    "Red FM": 12,
    Total: 236,
  },
  {
    Brand: "MCDONALD'S",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 114,
    "Radio One": 120,
    "Red FM": 0,
    Total: 234,
  },
  {
    Brand: "PANASONIC",
    Sector: "CONSUMER DURABLES",
    "Radio City": 189,
    "Radio Mirchi": 39,
    "Radio One": 0,
    "Red FM": 0,
    Total: 228,
  },
  {
    Brand: "BINGE CENTRAL",
    Sector: "FMCG",
    "Radio City": 220,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 220,
  },
  {
    Brand: "MUTUAL FUND",
    Sector: "FINANCE",
    "Radio City": 121,
    "Radio Mirchi": 56,
    "Radio One": 40,
    "Red FM": 0,
    Total: 217,
  },
  {
    Brand: "KAVERI BUILDTECH",
    Sector: "PROPERTY",
    "Radio City": 63,
    "Radio Mirchi": 79,
    "Radio One": 0,
    "Red FM": 75,
    Total: 217,
  },
  {
    Brand: "PATANJALI",
    Sector: "HEALTHCARE",
    "Radio City": 157,
    "Radio Mirchi": 60,
    "Radio One": 0,
    "Red FM": 0,
    Total: 217,
  },
  {
    Brand: "FORTIS HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 201,
    "Radio Mirchi": 8,
    "Radio One": 0,
    "Red FM": 0,
    Total: 209,
  },
  {
    Brand: "HAMDARD",
    Sector: "HEALTHCARE",
    "Radio City": 84,
    "Radio Mirchi": 42,
    "Radio One": 0,
    "Red FM": 79,
    Total: 205,
  },
  {
    Brand: "SUBHARTI UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 102,
    "Radio Mirchi": 102,
    "Radio One": 0,
    "Red FM": 0,
    Total: 204,
  },
  {
    Brand: "VOLTAS",
    Sector: "CONSUMER DURABLES",
    "Radio City": 52,
    "Radio Mirchi": 50,
    "Radio One": 50,
    "Red FM": 49,
    Total: 201,
  },
  {
    Brand: "HL CITY",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 100,
    "Radio One": 0,
    "Red FM": 101,
    Total: 201,
  },
  {
    Brand: "CAMPHOR-BASED AIR FRESHENER",
    Sector: "HOME FURNISHING",
    "Radio City": 0,
    "Radio Mirchi": 74,
    "Radio One": 0,
    "Red FM": 123,
    Total: 197,
  },
  {
    Brand: "LIC",
    Sector: "FINANCE",
    "Radio City": 150,
    "Radio Mirchi": 13,
    "Radio One": 34,
    "Red FM": 0,
    Total: 197,
  },
  {
    Brand: "NAVRAJ GROUP",
    Sector: "PROPERTY",
    "Radio City": 178,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 12,
    Total: 190,
  },
  {
    Brand: "HYUNDAI",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 122,
    "Radio One": 0,
    "Red FM": 66,
    Total: 188,
  },
  {
    Brand: "KIA",
    Sector: "AUTOMOBILE",
    "Radio City": 71,
    "Radio Mirchi": 70,
    "Radio One": 0,
    "Red FM": 45,
    Total: 186,
  },
  {
    Brand: "JEENA SIKHO HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 72,
    "Radio One": 108,
    "Red FM": 0,
    Total: 180,
  },
  {
    Brand: "HARIOM",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 179,
    Total: 179,
  },
  {
    Brand: "TITAN",
    Sector: "ACCESSORIES",
    "Radio City": 0,
    "Radio Mirchi": 86,
    "Radio One": 0,
    "Red FM": 82,
    Total: 168,
  },
  {
    Brand: "FRANCHISE INDIA 2025",
    Sector: "BUSINESS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 168,
    "Red FM": 0,
    Total: 168,
  },
  {
    Brand: "PRATAP SPORTS SCHOOL",
    Sector: "EDUCATION",
    "Radio City": 168,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 168,
  },
  {
    Brand: "FRANCHISE INDIA EXPO 2025",
    Sector: "EVENTS",
    "Radio City": 75,
    "Radio Mirchi": 91,
    "Radio One": 0,
    "Red FM": 0,
    Total: 166,
  },
  {
    Brand: "SPECTRUM METRO SECTOR 75",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 166,
    "Red FM": 0,
    Total: 166,
  },
  {
    Brand: "JEENA SIKHO",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 164,
    Total: 164,
  },
  {
    Brand: "PULSE",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 162,
    "Red FM": 0,
    Total: 162,
  },
  {
    Brand: "NUTRELA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 161,
    "Red FM": 0,
    Total: 161,
  },
  {
    Brand: "HDFC BANK",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 71,
    "Radio One": 0,
    "Red FM": 88,
    Total: 159,
  },
  {
    Brand: "INGRID BRA",
    Sector: "TEXTILES AND RETAIL",
    "Radio City": 148,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 148,
  },
  {
    Brand: "TATHASTU REALTIES",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 146,
    "Radio One": 0,
    "Red FM": 0,
    Total: 146,
  },
  {
    Brand: "DOUBLE CHABI",
    Sector: "FMCG",
    "Radio City": 143,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 143,
  },
  {
    Brand: "KELVINATOR",
    Sector: "CONSUMER DURABLES",
    "Radio City": 74,
    "Radio Mirchi": 69,
    "Radio One": 0,
    "Red FM": 0,
    Total: 143,
  },
  {
    Brand: "DWARKA EXPRESSWAY",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 139,
    Total: 139,
  },
  {
    Brand: "AAKASH INSTITUTE",
    Sector: "EDUCATION",
    "Radio City": 137,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 137,
  },
  {
    Brand: "RC SWAPPR",
    Sector: "ENTERTAINMENT",
    "Radio City": 136,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 136,
  },
  {
    Brand: "AAKASH",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 132,
    Total: 132,
  },
  {
    Brand: "MC DONALD'S",
    Sector: "FMCG",
    "Radio City": 130,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 130,
  },
  {
    Brand: "TOYOTA",
    Sector: "AUTOMOBILE",
    "Radio City": 60,
    "Radio Mirchi": 60,
    "Radio One": 0,
    "Red FM": 0,
    Total: 120,
  },
  {
    Brand: "VADILAAL",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 119,
    "Radio One": 0,
    "Red FM": 0,
    Total: 119,
  },
  {
    Brand: "CRICKET BLOCKBUSTER",
    Sector: "ENTERTAINMENT",
    "Radio City": 109,
    "Radio Mirchi": 5,
    "Radio One": 0,
    "Red FM": 0,
    Total: 114,
  },
  {
    Brand: "KUNDAN&POLKI JEWELRY",
    Sector: "ACCESSORIES",
    "Radio City": 111,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 111,
  },
  {
    Brand: "VIKRAM MILLS FRESH CHAKKI ATTA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 110,
    "Radio One": 0,
    "Red FM": 0,
    Total: 110,
  },
  {
    Brand: "SHANTA HOLDINGS",
    Sector: "PROPERTY",
    "Radio City": 109,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 109,
  },
  {
    Brand: "VALIDAAL",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 107,
    Total: 107,
  },
  {
    Brand: "ELECTRO",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 104,
    "Radio One": 0,
    "Red FM": 0,
    Total: 104,
  },
  {
    Brand: "DR. LAL",
    Sector: "HEALTHCARE",
    "Radio City": 96,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 96,
  },
  {
    Brand: "ICICI LOMBARD",
    Sector: "TRAVEL&TOURISM",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 94,
    "Red FM": 0,
    Total: 94,
  },
  {
    Brand: "IIMT GROUP OF COLLEGES",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 93,
    Total: 93,
  },
  {
    Brand: "VIDYA MANDIR CLASSES",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 44,
    "Red FM": 48,
    Total: 92,
  },
  {
    Brand: "GOLDEN CRUISER",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 87,
    "Radio One": 0,
    "Red FM": 0,
    Total: 87,
  },
  {
    Brand: "TATA IPL",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 73,
    "Radio One": 13,
    "Red FM": 0,
    Total: 86,
  },
  {
    Brand: "JOYALUKKAS",
    Sector: "ACCESSORIES",
    "Radio City": 84,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 84,
  },
  {
    Brand: "BRICK&BOLT",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 84,
    "Radio One": 0,
    "Red FM": 0,
    Total: 84,
  },
  {
    Brand: "JACK DANIELS",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 82,
    "Red FM": 0,
    Total: 82,
  },
  {
    Brand: "ZEE 5",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 82,
    Total: 82,
  },
  {
    Brand: "SWIGGY&ZOMATO",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 81,
    Total: 81,
  },
  {
    Brand: "RED FM",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 81,
    Total: 81,
  },
  {
    Brand: "NIIT UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 77,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 77,
  },
  {
    Brand: "DC FAN SABHA APP",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 72,
    "Red FM": 0,
    Total: 72,
  },
  {
    Brand: "SIYANO",
    Sector: "TECHNOLOGY",
    "Radio City": 0,
    "Radio Mirchi": 69,
    "Radio One": 0,
    "Red FM": 0,
    Total: 69,
  },
  {
    Brand: "FUN N FOOD WATER PARK",
    Sector: "ENTERTAINMENT",
    "Radio City": 68,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 68,
  },
  {
    Brand: "PET SAFFA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 67,
    "Radio One": 0,
    "Red FM": 0,
    Total: 67,
  },
  {
    Brand: "MUZAD DISCO",
    Sector: "ENTERTAINMENT",
    "Radio City": 67,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 67,
  },
  {
    Brand: "BIGBASKET",
    Sector: "E-COMMERCE",
    "Radio City": 0,
    "Radio Mirchi": 65,
    "Radio One": 0,
    "Red FM": 0,
    Total: 65,
  },
  {
    Brand: "FOREVER INDIA EVENTS",
    Sector: "ENTERTAINMENT",
    "Radio City": 65,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 65,
  },
  {
    Brand: "MUGLI GHUTTI 555",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 5,
    "Radio One": 0,
    "Red FM": 59,
    Total: 64,
  },
  {
    Brand: "NIC",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 64,
    "Radio One": 0,
    "Red FM": 0,
    Total: 64,
  },
  {
    Brand: "ARNEJA",
    Sector: "HOME FURNISHING",
    "Radio City": 0,
    "Radio Mirchi": 30,
    "Radio One": 0,
    "Red FM": 31,
    Total: 61,
  },
  {
    Brand: "BPL AIR CONDITIONER",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 59,
    "Radio One": 0,
    "Red FM": 0,
    Total: 59,
  },
  {
    Brand: "BPL",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 58,
    Total: 58,
  },
  {
    Brand: "MUGLI GHUTTI",
    Sector: "FMCG",
    "Radio City": 58,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 58,
  },
  {
    Brand: "BOOKMYSHOW",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 56,
    "Red FM": 0,
    Total: 56,
  },
  {
    Brand: "GENERAL INSURANCE COUNCIL",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 34,
    "Radio One": 0,
    "Red FM": 20,
    Total: 54,
  },
  {
    Brand: "DAYAL EYE CENTRE",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 51,
    Total: 51,
  },
  {
    Brand: "UNIVERSITY OF STIRLING",
    Sector: "EDUCATION",
    "Radio City": 50,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 50,
  },
  {
    Brand: "OSHAN WATER PARK",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 49,
    Total: 49,
  },
  {
    Brand: "VIDYAMANDIR CLASSES",
    Sector: "EDUCATION",
    "Radio City": 24,
    "Radio Mirchi": 17,
    "Radio One": 0,
    "Red FM": 0,
    Total: 41,
  },
  {
    Brand: "ZEE NEWS",
    Sector: "ENTERTAINMENT",
    "Radio City": 40,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 40,
  },
  {
    Brand: "RADIO CITY",
    Sector: "ENTERTAINMENT",
    "Radio City": 39,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 39,
  },
  {
    Brand: "KYC UPDATE SERVICE",
    Sector: "FINANCE",
    "Radio City": 38,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 38,
  },
  {
    Brand: "HERO CYCLES",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 38,
    Total: 38,
  },
  {
    Brand: "GENERALI HEALTH INSURANCE",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 5,
    "Radio One": 0,
    "Red FM": 33,
    Total: 38,
  },
  {
    Brand: "DR. MANDIP YADAV DENTAL&IMPLANT CENTER",
    Sector: "HEALTHCARE",
    "Radio City": 38,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 38,
  },
  {
    Brand: "SILK MARK",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 37,
    Total: 37,
  },
  {
    Brand: "LINGAYA'S VIDYAPEETH",
    Sector: "EDUCATION",
    "Radio City": 37,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 37,
  },
  {
    Brand: "NDMC",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 17,
    "Radio One": 0,
    "Red FM": 18,
    Total: 35,
  },
  {
    Brand: "HONDA ELEVATE",
    Sector: "AUTOMOBILE",
    "Radio City": 34,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 34,
  },
  {
    Brand: "PSRI HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 32,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 32,
  },
  {
    Brand: "MG MOTOR",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 31,
    "Radio One": 0,
    "Red FM": 0,
    Total: 31,
  },
  {
    Brand: "RBI",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 14,
    "Radio One": 15,
    "Red FM": 2,
    Total: 31,
  },
  {
    Brand: "ORS",
    Sector: "HEALTHCARE",
    "Radio City": 30,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 30,
  },
  {
    Brand: "FEDERAL BANK",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 30,
    Total: 30,
  },
  {
    Brand: "AURUM",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 30,
    Total: 30,
  },
  {
    Brand: "FEVER FM",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 29,
    "Red FM": 0,
    Total: 29,
  },
  {
    Brand: "POLITICAL SCIENCE CONFERENCE",
    Sector: "EVENTS",
    "Radio City": 29,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 29,
  },
  {
    Brand: "IDP EDUCATION",
    Sector: "EDUCATION",
    "Radio City": 29,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 29,
  },
  {
    Brand: "NFSU",
    Sector: "EDUCATION",
    "Radio City": 28,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 28,
  },
  {
    Brand: "VEEDOL",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 27,
    "Radio One": 0,
    "Red FM": 0,
    Total: 27,
  },
  {
    Brand: "JIO HOTSTAR",
    Sector: "ENTERTAINMENT",
    "Radio City": 10,
    "Radio Mirchi": 7,
    "Radio One": 0,
    "Red FM": 10,
    Total: 27,
  },
  {
    Brand: "HRIT UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 26,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 26,
  },
  {
    Brand: "KYC RBI AWARENESS CAMPAIGN",
    Sector: "FINANCE",
    "Radio City": 25,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 25,
  },
  {
    Brand: "YATHARTH HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 24,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "RADIO CITY – LOVE GURU SHOW",
    Sector: "ENTERTAINMENT",
    "Radio City": 24,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "SPRITE",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 23,
    "Radio One": 0,
    "Red FM": 0,
    Total: 23,
  },
  {
    Brand: "PAIN RELIEF OIL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 23,
    "Radio One": 0,
    "Red FM": 0,
    Total: 23,
  },
  {
    Brand: "JAGRAN PRASARAN",
    Sector: "PUBLIC INTEREST",
    "Radio City": 22,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 22,
  },
  {
    Brand: "GENERAL INSURANCE",
    Sector: "FINANCE",
    "Radio City": 20,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "ROOP MANTRA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 20,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "VIETJET AIR",
    Sector: "TRAVEL&TOURISM",
    "Radio City": 20,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "SACHI SAHELI",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 19,
    "Radio One": 0,
    "Red FM": 0,
    Total: 19,
  },
  {
    Brand: "EXHIBITION DELHI 17TH-18TH MAY 2025",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 19,
    "Radio One": 0,
    "Red FM": 0,
    Total: 19,
  },
  {
    Brand: "ANIME JUNCTION",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 19,
    "Red FM": 0,
    Total: 19,
  },
  {
    Brand: "DABUR COOL KING THANDA TEL",
    Sector: "PERSONAL CARE",
    "Radio City": 0,
    "Radio Mirchi": 19,
    "Radio One": 0,
    "Red FM": 0,
    Total: 19,
  },
  {
    Brand: "AMBIENCE MALL – LOUIS PHILIPPE",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 18,
    "Radio One": 0,
    "Red FM": 0,
    Total: 18,
  },
  {
    Brand: "NAYARA PETROL PUMP",
    Sector: "PETROLEUM PRODUCTS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 18,
    Total: 18,
  },
  {
    Brand: "STOCKGRO",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 16,
    "Red FM": 0,
    Total: 16,
  },
  {
    Brand: "HONDA AMAZE",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 15,
    "Radio One": 0,
    "Red FM": 0,
    Total: 15,
  },
  {
    Brand: "D.I.Y HEALTH",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 15,
    "Radio One": 0,
    "Red FM": 0,
    Total: 15,
  },
  {
    Brand: "FOOD&DELIVERY",
    Sector: "E-COMMERCE",
    "Radio City": 0,
    "Radio Mirchi": 14,
    "Radio One": 0,
    "Red FM": 0,
    Total: 14,
  },
  {
    Brand: "ACQUIRED CRED",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 14,
    "Radio One": 0,
    "Red FM": 0,
    Total: 14,
  },
  {
    Brand: "ARCHIES",
    Sector: "RETAIL",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 14,
    "Red FM": 0,
    Total: 14,
  },
  {
    Brand: "MANAPPURAM FINANCE",
    Sector: "FINANCE",
    "Radio City": 14,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 14,
  },
  {
    Brand: "PARIMATCH",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 13,
    "Radio One": 0,
    "Red FM": 0,
    Total: 13,
  },
  {
    Brand: "GAANA",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 13,
    "Radio One": 0,
    "Red FM": 0,
    Total: 13,
  },
  {
    Brand: "DELHI CAPITALS",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 13,
    "Red FM": 0,
    Total: 13,
  },
  {
    Brand: "BHIM",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 13,
    "Radio One": 0,
    "Red FM": 0,
    Total: 13,
  },
  {
    Brand: "JIOTV",
    Sector: "ENTERTAINMENT",
    "Radio City": 12,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 12,
  },
  {
    Brand: "SHARDA UPTOWN",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 12,
    Total: 12,
  },
  {
    Brand: "DEV DARSHAN DHOOP&AGARBATTI",
    Sector: "HOME FURNISHING",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 12,
    Total: 12,
  },
  {
    Brand: "BRIJ MEDICAL CENTRE",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 11,
    Total: 11,
  },
  {
    Brand: "BIS APP",
    Sector: "PUBLIC INTEREST",
    "Radio City": 11,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 11,
  },
  {
    Brand: "YAMUNA EXPRESSWAY",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 11,
    Total: 11,
  },
  {
    Brand: "SHAKTI AATA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 10,
    "Radio One": 0,
    "Red FM": 0,
    Total: 10,
  },
  {
    Brand: "CGTMSE",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 10,
    Total: 10,
  },
  {
    Brand: "NAYARA ENERGY",
    Sector: "PETROLEUM PRODUCTS",
    "Radio City": 0,
    "Radio Mirchi": 10,
    "Radio One": 0,
    "Red FM": 0,
    Total: 10,
  },
  {
    Brand: "LOUIS PHILIPPE-AMBIENCE MALL",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 9,
    Total: 9,
  },
  {
    Brand: "MAHINDRA",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 9,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "KIDZANIA",
    Sector: "CONSUMER DURABLES",
    "Radio City": 9,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "ISI",
    Sector: "MANUFACTURING",
    "Radio City": 9,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "DLF MALL OF INDIA",
    Sector: "RETAIL",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 9,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "DR ARTHO SPRAY",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 9,
    "Radio One": 0,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "SHUDDHI AYURVEDA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 8,
    "Radio One": 0,
    "Red FM": 0,
    Total: 8,
  },
  {
    Brand: "ZUNO",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 8,
    "Radio One": 0,
    "Red FM": 0,
    Total: 8,
  },
  {
    Brand: "MULTIPLE BRANDS PARTICIPATING IN THE SALE",
    Sector: "E-COMMERCE",
    "Radio City": 0,
    "Radio Mirchi": 8,
    "Radio One": 0,
    "Red FM": 0,
    Total: 8,
  },
  {
    Brand: "BANK OF BARODA",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 8,
    Total: 8,
  },
  {
    Brand: "ABHINANDAN LODHA – GOLDEN TRIANGLE",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 8,
    "Radio One": 0,
    "Red FM": 0,
    Total: 8,
  },
  {
    Brand: "MOTHER DAIRY",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 7,
    Total: 7,
  },
  {
    Brand: "VIDYA MANDIR",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 7,
    "Radio One": 0,
    "Red FM": 0,
    Total: 7,
  },
  {
    Brand: "DPXPO",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 6,
    "Radio One": 0,
    "Red FM": 0,
    Total: 6,
  },
  {
    Brand: "NADIADWALA GRANDSON ENTERTAINMENT",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 6,
    "Radio One": 0,
    "Red FM": 0,
    Total: 6,
  },
  {
    Brand: "DISNEY+ HOTSTAR",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 3,
    "Radio One": 0,
    "Red FM": 0,
    Total: 3,
  },
  {
    Brand: "MEDANTA‑MOOLCHAND HEART CENTRE",
    Sector: "HEALTHCARE",
    "Radio City": 2,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "LAAL PARI",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 2,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "DR CHANDRAKANT KAR",
    Sector: "HEALTHCARE",
    "Radio City": 2,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "DR. VIKAS CHOPRA",
    Sector: "HEALTHCARE",
    "Radio City": 2,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "TOP CREW AVIATION",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 2,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "OMNIS THE ELYSIUM",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 2,
    Total: 2,
  },
  {
    Brand: "HOLY FAMILY HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 2,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "GODREJ",
    Sector: "AGRICULTURE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 2,
    Total: 2,
  },
  {
    Brand: "SIR GANGA RAM HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 2,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 2,
  },
  {
    Brand: "DR. AGI G PILLAI HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 1,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 1,
  },
  {
    Brand: "DR. SAMEENA KHALIL",
    Sector: "HEALTHCARE",
    "Radio City": 1,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 1,
  },
  {
    Brand: "RENOX",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 1,
    Total: 1,
  },
];

export const week20 = [
  {
    Brand: "ATLANTIC WATER WORLD",
    Sector: "ENTERTAINMENT",
    "Radio City": 702,
    "Radio Mirchi": 522,
    "Radio One": 0,
    "Red FM": 0,
    Total: 1224,
  },
  {
    Brand: "UNISON JEWELS",
    Sector: "ACCESSORIES",
    "Radio City": 393,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 412,
    Total: 805,
  },
  {
    Brand: "SPINNY",
    Sector: "AUTOMOBILE",
    "Radio City": 191,
    "Radio Mirchi": 186,
    "Radio One": 166,
    "Red FM": 166,
    Total: 709,
  },
  {
    Brand: "WORLDS OF WONDER (WOW)",
    Sector: "ENTERTAINMENT",
    "Radio City": 458,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 250,
    Total: 708,
  },
  {
    Brand: "MARUTI SUZUKI",
    Sector: "AUTOMOBILE",
    "Radio City": 119,
    "Radio Mirchi": 155,
    "Radio One": 107,
    "Red FM": 264,
    Total: 645,
  },
  {
    Brand: "SBI",
    Sector: "PUBLIC INTEREST",
    "Radio City": 43,
    "Radio Mirchi": 75,
    "Radio One": 299,
    "Red FM": 153,
    Total: 570,
  },
  {
    Brand: "VIMAL",
    Sector: "FMCG",
    "Radio City": 153,
    "Radio Mirchi": 132,
    "Radio One": 126,
    "Red FM": 127,
    Total: 538,
  },
  {
    Brand: "CANARA BANK",
    Sector: "FINANCE",
    "Radio City": 324,
    "Radio Mirchi": 79,
    "Radio One": 0,
    "Red FM": 113,
    Total: 516,
  },
  {
    Brand: "ALLEN CAREER INSTITUTE",
    Sector: "EDUCATION",
    "Radio City": 155,
    "Radio Mirchi": 148,
    "Radio One": 0,
    "Red FM": 145,
    Total: 448,
  },
  {
    Brand: "NISSAN",
    Sector: "AUTOMOBILE",
    "Radio City": 441,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 441,
  },
  {
    Brand: "NAVRAJ GROUP",
    Sector: "PROPERTY",
    "Radio City": 324,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 116,
    Total: 440,
  },
  {
    Brand: "ROF",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 346,
    Total: 346,
  },
  {
    Brand: "ACE VERDE",
    Sector: "PROPERTY",
    "Radio City": 166,
    "Radio Mirchi": 179,
    "Radio One": 0,
    "Red FM": 0,
    Total: 345,
  },
  {
    Brand: "FRANCHISE INDIA EXPO 2025",
    Sector: "ENTERTAINMENT",
    "Radio City": 82,
    "Radio Mirchi": 127,
    "Radio One": 119,
    "Red FM": 0,
    Total: 328,
  },
  {
    Brand: "PANASONIC",
    Sector: "CONSUMER DURABLES",
    "Radio City": 260,
    "Radio Mirchi": 41,
    "Radio One": 0,
    "Red FM": 0,
    Total: 301,
  },
  {
    Brand: "CRICKET BLOCKBUSTER",
    Sector: "ENTERTAINMENT",
    "Radio City": 297,
    "Radio Mirchi": 2,
    "Radio One": 0,
    "Red FM": 0,
    Total: 299,
  },
  {
    Brand: "CULT.FIT",
    Sector: "HEALTH&FITNESS",
    "Radio City": 0,
    "Radio Mirchi": 159,
    "Radio One": 132,
    "Red FM": 0,
    Total: 291,
  },
  {
    Brand: "HAMDARD",
    Sector: "HEALTHCARE",
    "Radio City": 82,
    "Radio Mirchi": 98,
    "Radio One": 0,
    "Red FM": 106,
    Total: 286,
  },
  {
    Brand: "VINRA GROUP",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 284,
    Total: 284,
  },
  {
    Brand: "K.R. MANGALAM UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 140,
    "Radio One": 0,
    "Red FM": 139,
    Total: 279,
  },
  {
    Brand: "HONDA",
    Sector: "AUTOMOBILE",
    "Radio City": 68,
    "Radio Mirchi": 65,
    "Radio One": 0,
    "Red FM": 146,
    Total: 279,
  },
  {
    Brand: "LG",
    Sector: "CONSUMER DURABLES",
    "Radio City": 108,
    "Radio Mirchi": 93,
    "Radio One": 57,
    "Red FM": 0,
    Total: 258,
  },
  {
    Brand: "RAJDHANI",
    Sector: "FMCG",
    "Radio City": 95,
    "Radio Mirchi": 47,
    "Radio One": 0,
    "Red FM": 109,
    Total: 251,
  },
  {
    Brand: "HYUNDAI",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 125,
    "Radio One": 0,
    "Red FM": 123,
    Total: 248,
  },
  {
    Brand: "KAVERI BUILDTECH",
    Sector: "PROPERTY",
    "Radio City": 80,
    "Radio Mirchi": 80,
    "Radio One": 0,
    "Red FM": 79,
    Total: 239,
  },
  {
    Brand: "ELECTRONICS MART JANAKPURI",
    Sector: "RETAIL",
    "Radio City": 0,
    "Radio Mirchi": 120,
    "Radio One": 0,
    "Red FM": 118,
    Total: 238,
  },
  {
    Brand: "PATANJALI",
    Sector: "HEALTHCARE",
    "Radio City": 173,
    "Radio Mirchi": 58,
    "Radio One": 0,
    "Red FM": 0,
    Total: 231,
  },
  {
    Brand: "DOUBLE CHABI",
    Sector: "FMCG",
    "Radio City": 227,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 227,
  },
  {
    Brand: "SHANTA HOLDINGS",
    Sector: "PROPERTY",
    "Radio City": 227,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 227,
  },
  {
    Brand: "MG",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 26,
    "Radio One": 0,
    "Red FM": 200,
    Total: 226,
  },
  {
    Brand: "LIC",
    Sector: "FINANCE",
    "Radio City": 86,
    "Radio Mirchi": 48,
    "Radio One": 64,
    "Red FM": 28,
    Total: 226,
  },
  {
    Brand: "KUNDAN&POLKI JEWELRY",
    Sector: "ACCESSORIES",
    "Radio City": 226,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 226,
  },
  {
    Brand: "INGRID BRA",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 226,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 226,
  },
  {
    Brand: "MUTUAL FUND",
    Sector: "FINANCE",
    "Radio City": 50,
    "Radio Mirchi": 76,
    "Radio One": 26,
    "Red FM": 62,
    Total: 214,
  },
  {
    Brand: "SUBHARTI UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 109,
    "Radio Mirchi": 104,
    "Radio One": 0,
    "Red FM": 0,
    Total: 213,
  },
  {
    Brand: "BINGE CENTRAL",
    Sector: "FMCG",
    "Radio City": 213,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 213,
  },
  {
    Brand: "DAAWAT",
    Sector: "FMCG",
    "Radio City": 95,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 115,
    Total: 210,
  },
  {
    Brand: "TATA MOTORS",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 200,
    "Radio One": 0,
    "Red FM": 0,
    Total: 200,
  },
  {
    Brand: "CAMPHOR-BASED AIR FRESHENER",
    Sector: "HOME FURNISHING",
    "Radio City": 0,
    "Radio Mirchi": 69,
    "Radio One": 0,
    "Red FM": 131,
    Total: 200,
  },
  {
    Brand: "SPECTRUM METRO SECTOR 75",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 193,
    "Red FM": 0,
    Total: 193,
  },
  {
    Brand: "GRAPHIC ERA UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 1,
    "Radio Mirchi": 98,
    "Radio One": 0,
    "Red FM": 93,
    Total: 192,
  },
  {
    Brand: "VOLTAS",
    Sector: "CONSUMER DURABLES",
    "Radio City": 40,
    "Radio Mirchi": 61,
    "Radio One": 44,
    "Red FM": 47,
    Total: 192,
  },
  {
    Brand: "PULSE",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 188,
    "Red FM": 0,
    Total: 188,
  },
  {
    Brand: "NUTRELA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 188,
    "Red FM": 0,
    Total: 188,
  },
  {
    Brand: "VI 5G MOBILE NETWORK",
    Sector: "TELECOMMUNICATIONS",
    "Radio City": 0,
    "Radio Mirchi": 95,
    "Radio One": 0,
    "Red FM": 89,
    Total: 184,
  },
  {
    Brand: "RC SWAPPR",
    Sector: "ENTERTAINMENT",
    "Radio City": 184,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 184,
  },
  {
    Brand: "ELECTRONIC MART JANAKPURI",
    Sector: "CONSUMER DURABLES",
    "Radio City": 182,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 182,
  },
  {
    Brand: "MG MOTOR",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 182,
    "Radio One": 0,
    "Red FM": 0,
    Total: 182,
  },
  {
    Brand: "TOYOTA",
    Sector: "AUTOMOBILE",
    "Radio City": 92,
    "Radio Mirchi": 89,
    "Radio One": 0,
    "Red FM": 0,
    Total: 181,
  },
  {
    Brand: "DWARKA EXPRESSWAY",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 179,
    Total: 179,
  },
  {
    Brand: "JURASIK PARK",
    Sector: "ENTERTAINMENT",
    "Radio City": 176,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 176,
  },
  {
    Brand: "UNIVERSITY OF STIRLING",
    Sector: "EDUCATION",
    "Radio City": 169,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 169,
  },
  {
    Brand: "HARYANA SHEHRI VIKAS PRADHIKARAN",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 84,
    "Radio One": 0,
    "Red FM": 84,
    Total: 168,
  },
  {
    Brand: "TATHASTU REALTIES",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 167,
    "Radio One": 0,
    "Red FM": 0,
    Total: 167,
  },
  {
    Brand: "JURASIK PARK INN",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 166,
    "Radio One": 0,
    "Red FM": 0,
    Total: 166,
  },
  {
    Brand: "HAMDARD ROOHAFZA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 83,
    "Radio One": 0,
    "Red FM": 79,
    Total: 162,
  },
  {
    Brand: "FUN N FOOD WATER PARK",
    Sector: "ENTERTAINMENT",
    "Radio City": 160,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 160,
  },
  {
    Brand: "GENERAL INSURANCE COUNCIL",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 43,
    "Radio One": 0,
    "Red FM": 113,
    Total: 156,
  },
  {
    Brand: "NIC",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 77,
    "Radio One": 0,
    "Red FM": 76,
    Total: 153,
  },
  {
    Brand: "IPC INTERNATIONAL EDUCATION",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 148,
    Total: 148,
  },
  {
    Brand: "GENERALI HEALTH INSURANCE",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 45,
    "Radio One": 0,
    "Red FM": 96,
    Total: 141,
  },
  {
    Brand: "DAIKIN",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 67,
    "Radio One": 0,
    "Red FM": 69,
    Total: 136,
  },
  {
    Brand: "NAYARA PETROL PUMP",
    Sector: "PETROLEUM PRODUCTS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 136,
    Total: 136,
  },
  {
    Brand: "VIKRAM MILLS FRESH CHAKKI ATTA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 134,
    "Radio One": 0,
    "Red FM": 0,
    Total: 134,
  },
  {
    Brand: "AAKASH INSTITUTE",
    Sector: "EDUCATION",
    "Radio City": 134,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 134,
  },
  {
    Brand: "AAKASH",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 128,
    Total: 128,
  },
  {
    Brand: "JACK DANIELS",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 127,
    "Red FM": 0,
    Total: 127,
  },
  {
    Brand: "DABUR COOL KING THANDA TEL",
    Sector: "PERSONAL CARE",
    "Radio City": 0,
    "Radio Mirchi": 125,
    "Radio One": 0,
    "Red FM": 0,
    Total: 125,
  },
  {
    Brand: "MC DONALD'S",
    Sector: "FMCG",
    "Radio City": 117,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 117,
  },
  {
    Brand: "VALIDAAL",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 114,
    Total: 114,
  },
  {
    Brand: "SHARDA UPTOWN",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 114,
    Total: 114,
  },
  {
    Brand: "VADILAAL",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 114,
    "Radio One": 0,
    "Red FM": 0,
    Total: 114,
  },
  {
    Brand: "KIA",
    Sector: "AUTOMOBILE",
    "Radio City": 42,
    "Radio Mirchi": 38,
    "Radio One": 0,
    "Red FM": 33,
    Total: 113,
  },
  {
    Brand: "MCDONALD'S",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 58,
    "Radio One": 54,
    "Red FM": 0,
    Total: 112,
  },
  {
    Brand: "CRAFT HOMES",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 109,
    Total: 109,
  },
  {
    Brand: "ELECTRO",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 104,
    "Radio One": 0,
    "Red FM": 0,
    Total: 104,
  },
  {
    Brand: "IIMT GROUP OF COLLEGES",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 104,
    Total: 104,
  },
  {
    Brand: "SAFAL STORE",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 104,
    Total: 104,
  },
  {
    Brand: "SANSKAR SHIKSHA SANGH",
    Sector: "EDUCATION",
    "Radio City": 103,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 103,
  },
  {
    Brand: "MOTHER DAIRY",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 101,
    Total: 101,
  },
  {
    Brand: "JIOMART",
    Sector: "E-COMMERCE",
    "Radio City": 0,
    "Radio Mirchi": 99,
    "Radio One": 0,
    "Red FM": 0,
    Total: 99,
  },
  {
    Brand: "SKODA",
    Sector: "AUTOMOBILE",
    "Radio City": 28,
    "Radio Mirchi": 28,
    "Radio One": 0,
    "Red FM": 37,
    Total: 93,
  },
  {
    Brand: "HSVP",
    Sector: "PUBLIC INTEREST",
    "Radio City": 87,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 87,
  },
  {
    Brand: "GOLDEN CRUISER",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 87,
    "Radio One": 0,
    "Red FM": 0,
    Total: 87,
  },
  {
    Brand: "ICICI LOMBARD",
    Sector: "TRAVEL&TOURISM",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 86,
    "Red FM": 0,
    Total: 86,
  },
  {
    Brand: "YATHARTH HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 84,
    "Radio One": 0,
    "Red FM": 0,
    Total: 84,
  },
  {
    Brand: "BRICK&BOLT",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 70,
    "Radio One": 0,
    "Red FM": 13,
    Total: 83,
  },
  {
    Brand: "MANAPPURAM FINANCE",
    Sector: "FINANCE",
    "Radio City": 81,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 81,
  },
  {
    Brand: "HITACHI",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 40,
    "Radio One": 0,
    "Red FM": 40,
    Total: 80,
  },
  {
    Brand: "MUZAD DISCO",
    Sector: "ENTERTAINMENT",
    "Radio City": 77,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 77,
  },
  {
    Brand: "TITAN",
    Sector: "ACCESSORIES",
    "Radio City": 0,
    "Radio Mirchi": 45,
    "Radio One": 0,
    "Red FM": 32,
    Total: 77,
  },
  {
    Brand: "RADIO CITY – LOVE GURU SHOW",
    Sector: "ENTERTAINMENT",
    "Radio City": 75,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 75,
  },
  {
    Brand: "HONDA AMAZE",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 75,
    "Radio One": 0,
    "Red FM": 0,
    Total: 75,
  },
  {
    Brand: "NIIT UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 74,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 74,
  },
  {
    Brand: "LINGAYA'S VIDYAPEETH",
    Sector: "EDUCATION",
    "Radio City": 73,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 73,
  },
  {
    Brand: "NAYARA ENERGY",
    Sector: "PETROLEUM PRODUCTS",
    "Radio City": 0,
    "Radio Mirchi": 73,
    "Radio One": 0,
    "Red FM": 0,
    Total: 73,
  },
  {
    Brand: "FEVER FM",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 73,
    "Red FM": 0,
    Total: 73,
  },
  {
    Brand: "SPRITE",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 72,
    "Radio One": 0,
    "Red FM": 0,
    Total: 72,
  },
  {
    Brand: "GAUTAM BUDDHA UNIVERSITY(GBU)",
    Sector: "EDUCATION",
    "Radio City": 40,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 32,
    Total: 72,
  },
  {
    Brand: "HRIT UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 72,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 72,
  },
  {
    Brand: "HONDA ELEVATE",
    Sector: "AUTOMOBILE",
    "Radio City": 71,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 71,
  },
  {
    Brand: "SIYANO",
    Sector: "TECHNOLOGY",
    "Radio City": 0,
    "Radio Mirchi": 68,
    "Radio One": 0,
    "Red FM": 0,
    Total: 68,
  },
  {
    Brand: "AMBIENCE MALL – LOUIS PHILIPPE",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 65,
    "Radio One": 0,
    "Red FM": 0,
    Total: 65,
  },
  {
    Brand: "D.I.Y HEALTH",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 64,
    "Radio One": 0,
    "Red FM": 0,
    Total: 64,
  },
  {
    Brand: "LOUIS PHILIPPE-AMBIENCE MALL",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 63,
    Total: 63,
  },
  {
    Brand: "DC FAN SABHA APP",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 63,
    "Red FM": 0,
    Total: 63,
  },
  {
    Brand: "JOYALUKKAS",
    Sector: "ACCESSORIES",
    "Radio City": 60,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 60,
  },
  {
    Brand: "BHARATI VIDYAPEETH DELHI",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 59,
    Total: 59,
  },
  {
    Brand: "BIGBASKET",
    Sector: "E-COMMERCE",
    "Radio City": 0,
    "Radio Mirchi": 58,
    "Radio One": 0,
    "Red FM": 0,
    Total: 58,
  },
  {
    Brand: "PET SAFFA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 55,
    "Radio One": 0,
    "Red FM": 0,
    Total: 55,
  },
  {
    Brand: "TATA IPL",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 38,
    "Radio One": 17,
    "Red FM": 0,
    Total: 55,
  },
  {
    Brand: "IILM UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 51,
    Total: 51,
  },
  {
    Brand: "CARATLANE",
    Sector: "ACCESSORIES",
    "Radio City": 0,
    "Radio Mirchi": 49,
    "Radio One": 0,
    "Red FM": 0,
    Total: 49,
  },
  {
    Brand: "LOUIS PHILIPPE",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 49,
    "Red FM": 0,
    Total: 49,
  },
  {
    Brand: "VIDYA MANDIR",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 4,
    "Radio One": 0,
    "Red FM": 44,
    Total: 48,
  },
  {
    Brand: "DAYAL EYE CENTRE",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 48,
    Total: 48,
  },
  {
    Brand: "DR. MANDIP YADAV DENTAL&IMPLANT CENTER",
    Sector: "HEALTHCARE",
    "Radio City": 48,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 48,
  },
  {
    Brand: "VIDYA MANDIR CLASSES",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 47,
    "Red FM": 0,
    Total: 47,
  },
  {
    Brand: "PUNJAB NATIONAL BANK",
    Sector: "FINANCE",
    "Radio City": 47,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 47,
  },
  {
    Brand: "DELHI CAPITALS",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 46,
    "Red FM": 0,
    Total: 46,
  },
  {
    Brand: "FORTIS HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 35,
    "Radio Mirchi": 8,
    "Radio One": 0,
    "Red FM": 0,
    Total: 43,
  },
  {
    Brand: "BHIM",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 43,
    "Radio One": 0,
    "Red FM": 0,
    Total: 43,
  },
  {
    Brand: "FOREVER INDIA EVENTS",
    Sector: "ENTERTAINMENT",
    "Radio City": 42,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 42,
  },
  {
    Brand: "ABHINANDAN LODHA – GOLDEN TRIANGLE",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 41,
    "Radio One": 0,
    "Red FM": 0,
    Total: 41,
  },
  {
    Brand: "AURUM",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 41,
    Total: 41,
  },
  {
    Brand: "BOOKMYSHOW",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 41,
    "Red FM": 0,
    Total: 41,
  },
  {
    Brand: "GENERAL INSURANCE",
    Sector: "FINANCE",
    "Radio City": 40,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 40,
  },
  {
    Brand: "AD : GARWARE",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 40,
    "Radio One": 0,
    "Red FM": 0,
    Total: 40,
  },
  {
    Brand: "DO NOT DISTURB(DND)",
    Sector: "PUBLIC INTEREST",
    "Radio City": 12,
    "Radio Mirchi": 14,
    "Radio One": 0,
    "Red FM": 12,
    Total: 38,
  },
  {
    Brand: "RADIO CITY",
    Sector: "ENTERTAINMENT",
    "Radio City": 35,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 35,
  },
  {
    Brand: "VIDYAMANDIR CLASSES",
    Sector: "EDUCATION",
    "Radio City": 16,
    "Radio Mirchi": 16,
    "Radio One": 0,
    "Red FM": 0,
    Total: 32,
  },
  {
    Brand: "GO GREEN AND CLEAN BY POWERGRID",
    Sector: "PUBLIC INTEREST",
    "Radio City": 32,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 32,
  },
  {
    Brand: "PRATAP SPORTS SCHOOL",
    Sector: "EDUCATION",
    "Radio City": 32,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 32,
  },
  {
    Brand: "PSRI HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 30,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 30,
  },
  {
    Brand: "NFSU",
    Sector: "EDUCATION",
    "Radio City": 29,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 29,
  },
  {
    Brand: "ENDORSED ORTHODONTICS",
    Sector: "HEALTHCARE",
    "Radio City": 29,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 29,
  },
  {
    Brand: "JIO HOTSTAR",
    Sector: "ENTERTAINMENT",
    "Radio City": 13,
    "Radio Mirchi": 1,
    "Radio One": 0,
    "Red FM": 15,
    Total: 29,
  },
  {
    Brand: "MAHINDRA",
    Sector: "AUTOMOBILE",
    "Radio City": 11,
    "Radio Mirchi": 0,
    "Radio One": 18,
    "Red FM": 0,
    Total: 29,
  },
  {
    Brand: "ANIME JUNCTION",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 27,
    "Red FM": 0,
    Total: 27,
  },
  {
    Brand: "KYC RBI AWARENESS CAMPAIGN",
    Sector: "FINANCE",
    "Radio City": 27,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 27,
  },
  {
    Brand: "PAIN RELIEF OIL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 26,
    "Radio One": 0,
    "Red FM": 0,
    Total: 26,
  },
  {
    Brand: "JIOTV",
    Sector: "ENTERTAINMENT",
    "Radio City": 25,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 25,
  },
  {
    Brand: "GOVERNMENT OF PUNJAB",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 24,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "HEALTH MINISTRY OF INDIA",
    Sector: "HEALTHCARE",
    "Radio City": 24,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "PURAB PREMIUM APARTMENT-SECTOR 88-MOHALI",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 24,
    Total: 24,
  },
  {
    Brand: "GMADA",
    Sector: "PROPERTY",
    "Radio City": 24,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "I.T.S COLLEGE",
    Sector: "EDUCATION",
    "Radio City": 24,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "KIDZANIA",
    Sector: "CONSUMER DURABLES",
    "Radio City": 24,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "ZUNO HEALTH INSURANCE",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 24,
    "Radio One": 0,
    "Red FM": 0,
    Total: 24,
  },
  {
    Brand: "VIETJET AIR",
    Sector: "TRAVEL&TOURISM",
    "Radio City": 23,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 23,
  },
  {
    Brand: "RADIO ONE",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 23,
    "Red FM": 0,
    Total: 23,
  },
  {
    Brand: "IDP EDUCATION",
    Sector: "EDUCATION",
    "Radio City": 21,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 21,
  },
  {
    Brand: "BANK OF BARODA",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 21,
    Total: 21,
  },
  {
    Brand: "PARIMATCH",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 20,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "CARRER LAUNCHER",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 20,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "CAREER LAUNCHER",
    Sector: "EDUCATION",
    "Radio City": 20,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "GLA UNIVERSITY",
    Sector: "EDUCATION",
    "Radio City": 10,
    "Radio Mirchi": 10,
    "Radio One": 0,
    "Red FM": 0,
    Total: 20,
  },
  {
    Brand: "FEDERAL BANK",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 19,
    Total: 19,
  },
  {
    Brand: "ROOP MANTRA",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 19,
    "Radio One": 0,
    "Red FM": 0,
    Total: 19,
  },
  {
    Brand: "ZEE NEWS",
    Sector: "ENTERTAINMENT",
    "Radio City": 19,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 19,
  },
  {
    Brand: "INDIAN SOCIETY FOR CLINICAL RESEARCH (ISCR)",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 18,
    "Radio One": 0,
    "Red FM": 0,
    Total: 18,
  },
  {
    Brand: "SACHI SAHELI",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 18,
    "Radio One": 0,
    "Red FM": 0,
    Total: 18,
  },
  {
    Brand: "SHYAM BALRAM",
    Sector: "ENTERTAINMENT",
    "Radio City": 16,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 16,
  },
  {
    Brand: "AD : SKODA",
    Sector: "AUTOMOBILE",
    "Radio City": 0,
    "Radio Mirchi": 14,
    "Radio One": 0,
    "Red FM": 0,
    Total: 14,
  },
  {
    Brand: "BASKIN-ROBBINS",
    Sector: "FMCG",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 14,
    Total: 14,
  },
  {
    Brand: "AD : HOUSEFULL 5 (2025)",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 14,
    "Radio One": 0,
    "Red FM": 0,
    Total: 14,
  },
  {
    Brand: "RBI",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 10,
    "Radio One": 3,
    "Red FM": 1,
    Total: 14,
  },
  {
    Brand: "DR. ZUBIN DEV SHARMA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 13,
    Total: 13,
  },
  {
    Brand: "PANDIT JEWELS",
    Sector: "ACCESSORIES",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 13,
    Total: 13,
  },
  {
    Brand: "HT MEDIA",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 13,
    "Red FM": 0,
    Total: 13,
  },
  {
    Brand: "DABUR",
    Sector: "PERSONAL CARE",
    "Radio City": 0,
    "Radio Mirchi": 12,
    "Radio One": 0,
    "Red FM": 0,
    Total: 12,
  },
  {
    Brand: "BIS APP",
    Sector: "PUBLIC INTEREST",
    "Radio City": 12,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 12,
  },
  {
    Brand: "JAGRAN PRASARAN",
    Sector: "PUBLIC INTEREST",
    "Radio City": 11,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 11,
  },
  {
    Brand: "AD : BARBEQUE NATION",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 9,
    "Radio One": 0,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "NARAYANA HOSPITAL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 9,
    "Radio One": 0,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "V DOT",
    Sector: "TEXTILES&APPARELS",
    "Radio City": 0,
    "Radio Mirchi": 9,
    "Radio One": 0,
    "Red FM": 0,
    Total: 9,
  },
  {
    Brand: "TIMEZONE",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 8,
    Total: 8,
  },
  {
    Brand: "ISI",
    Sector: "PUBLIC INTEREST",
    "Radio City": 8,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 8,
  },
  {
    Brand: "RATRA DENTAL CENTER",
    Sector: "HEALTHCARE",
    "Radio City": 8,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 8,
  },
  {
    Brand: "RED FM",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 8,
    Total: 8,
  },
  {
    Brand: "DR. SHARAD MALHOTRA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 8,
    Total: 8,
  },
  {
    Brand: "DELHI PUBLIC SCHOOL",
    Sector: "EDUCATION",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 7,
    Total: 7,
  },
  {
    Brand: "DR ARTHO SPRAY",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 7,
    "Radio One": 0,
    "Red FM": 0,
    Total: 7,
  },
  {
    Brand: "DR AJAY BHALLA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 7,
    Total: 7,
  },
  {
    Brand: "DR ACHAL GARAK",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 7,
    Total: 7,
  },
  {
    Brand: "SAREGAMA",
    Sector: "ENTERTAINMENT",
    "Radio City": 7,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 7,
  },
  {
    Brand: "LODHA – GOLDEN TRIANGLE",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 7,
    "Radio One": 0,
    "Red FM": 0,
    Total: 7,
  },
  {
    Brand: "AD : DAVA INDIA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 6,
    "Radio One": 0,
    "Red FM": 0,
    Total: 6,
  },
  {
    Brand: "DR. LALIT SHARMA",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 6,
    Total: 6,
  },
  {
    Brand: "DR. LAL",
    Sector: "HEALTHCARE",
    "Radio City": 5,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 0,
    Total: 5,
  },
  {
    Brand: "MINISTRY OF EDUCATION",
    Sector: "PUBLIC INTEREST",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 4,
    Total: 4,
  },
  {
    Brand: "DEV DARSHAN DHOOP&AGARBATTI",
    Sector: "HOME FURNISHING",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 3,
    Total: 3,
  },
  {
    Brand: "DR. RAHUL",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 3,
    Total: 3,
  },
  {
    Brand: "HL CITY",
    Sector: "PROPERTY",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 2,
    Total: 2,
  },
  {
    Brand: "BPL",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 1,
    Total: 1,
  },
  {
    Brand: "DR.ROHAN",
    Sector: "HEALTHCARE",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 1,
    Total: 1,
  },
  {
    Brand: "FOOD&DELIVERY",
    Sector: "E-COMMERCE",
    "Radio City": 0,
    "Radio Mirchi": 1,
    "Radio One": 0,
    "Red FM": 0,
    Total: 1,
  },
  {
    Brand: "HARIOM",
    Sector: "CONSUMER DURABLES",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 1,
    Total: 1,
  },
  {
    Brand: "OSHAN WATER PARK",
    Sector: "ENTERTAINMENT",
    "Radio City": 0,
    "Radio Mirchi": 0,
    "Radio One": 0,
    "Red FM": 1,
    Total: 1,
  },
  {
    Brand: "ZUNO",
    Sector: "FINANCE",
    "Radio City": 0,
    "Radio Mirchi": 1,
    "Radio One": 0,
    "Red FM": 0,
    Total: 1,
  },
];
